proxy_newen:
  server: "103.207.36.217:8039"
  username: "username"
  password: "password"
  link_request_proxy: "https://api.zingproxy.com/getip/f768de4ff0559cb15c77e270061bba76af4bf9d1"
account:
  username: "username"
  password: "password"