proxy_newen:
  server: "123.207.36.217:8029"
  username: "proxy_username"
  password: "proxy_password"
  link_request_proxy: "https://api.zingproxy.com/getip/f768de4ff0559cb270061bba76af4bf9d1"
account:
  username: "tiktok_username"
  password: "tiktok_password"